spring:
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/logs.yml"

  datasource:
    url: jdbc:hsqldb:mem:test8;sql.syntax_pgs=true;allow_empty_batch=true
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none